### ISSUE TITLE
Got error message when excute to.dfs

### ISSUE THREAD

**Issue by chsteven** [RevolutionAnalytics/rmr2#104]
Hi,
when I execute  train.hdfs = to.dfs(keyval(train$user,train))  where train.hdfs come from a .csv file that have 15000 records, 3 fields per record. there are some error msg. 

The messages: 
"Error in writeBin(.Call("typedbytes_writer", objects, native, PACKAGE = "rmr2"),  :
  long vectors not supported yet: connections.c:4078"

**Comment by mallik1** [comment]
is it resolved please,i got same issue .
