### ISSUE TITLE
PipeMapRed.waitOutputThreads(): subprocess failed with code 1

### ISSUE THREAD

**Issue by Poornesh** [RevolutionAnalytics/rmr2#156]
Hi Team,
        Unable to run the R code, got the below error while running. Could you please help me to resolve this as soon as possible.

Job i am running
-----------------------------
$bin/hadoop jar ${HADOOP_STREAMING}.jar  -D mapreduce.job.reduces=0 -inputformat org.apache.hadoop.mapred.TextInputFormat -input /user/hduser/gutenberg -output /user/hduser/gutenberg-output -mapper HCS.R -file HCS.R

packageJobJar: [HCS.R, /app/hadoop/tmp/hadoop-unjar6972070348115862750/] [] /tmp/streamjob7441587082854739637.jar tmpDir=null
15/01/20 19:24:18 INFO util.NativeCodeLoader: Loaded the native-hadoop library
15/01/20 19:24:18 WARN snappy.LoadSnappy: Snappy native library not loaded
15/01/20 19:24:18 INFO mapred.FileInputFormat: Total input paths to process : 1
15/01/20 19:24:18 INFO streaming.StreamJob: getLocalDirs(): [/app/hadoop/tmp/mapred/local]
15/01/20 19:24:18 INFO streaming.StreamJob: Running job: job_201501201850_0002
15/01/20 19:24:18 INFO streaming.StreamJob: To kill this job, run:
15/01/20 19:24:18 INFO streaming.StreamJob: /usr/local/hadoop/libexec/../bin/hadoop job  -Dmapred.job.tracker=localhost:54311 -kill job_201501201850_0002
15/01/20 19:24:18 INFO streaming.StreamJob: Tracking URL: http://localhost:50030/jobdetails.jsp?jobid=job_201501201850_0002
15/01/20 19:24:19 INFO streaming.StreamJob:  map 0%  reduce 0%
15/01/20 19:24:50 INFO streaming.StreamJob:  map 100%  reduce 100%
15/01/20 19:24:50 INFO streaming.StreamJob: To kill this job, run:
15/01/20 19:24:50 INFO streaming.StreamJob: /usr/local/hadoop/libexec/../bin/hadoop job  -Dmapred.job.tracker=localhost:54311 -kill job_201501201850_0002
15/01/20 19:24:50 INFO streaming.StreamJob: Tracking URL: http://localhost:50030/jobdetails.jsp?jobid=job_201501201850_0002
15/01/20 19:24:50 ERROR streaming.StreamJob: Job not successful. Error: # of failed Map Tasks exceeded allowed limit. FailedCount: 1. LastFailedTask: task_201501201850_0002_m_000000
15/01/20 19:24:50 INFO streaming.StreamJob: killJob...
Streaming Command Failed!

Error from logs  below:
------------------------------

INFO org.apache.hadoop.mapred.TaskInProgress: Error from attempt_201501201850_0001_m_000001_0: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
        at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:362)                                                       
	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:576)
	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:135)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:57)
	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:36)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:430)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:366)
	at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.Child.main(Child.java:249)

**Comment by piccolbo** [comment]
I think you are posting on the wrong issue tracker. I don't see any use of rmr2 here. You are not supposed to call streaming directly, that's the internal implementation but nothing users should touch. Read the manual first, or use at your own peril.

**Comment by Poornesh** [comment]
where i can find a manuval ?
could you please send to mail : poornesha.gowda@gmail.com 
Thanks in advance..

**Comment by piccolbo** [comment]
I'd recommend the Google search engine, http://google.com

**Comment by Poornesh** [comment]
The problem is in declaring arguments, HCS code is working for R but not with Rhadoop.
whats wrong with the below command. pls...

bin/hadoop jar ${HADOOP_STREAMING}*jar -D mapreduce.job.reduces=0 -input /user/hduser/gutenberg -output /user/hduser/gutenberg-output -mapper pwd/HCS.R -file pwd/HCS.R
