### ISSUE TITLE
Mapreduce warning: namespace 'rmr2' is not available and has been replaced

### ISSUE THREAD

**Issue by neustre** [RevolutionAnalytics/rmr2#171]
hi , i have this problem for a week now , first of all i have one node with hadoop and Rstudio in it .
when i want to run this program : 

---

ints = to.dfs(1:100)
calc = mapreduce(input = ints, map = function(k, v) cbind(v, 2*v))
from.dfs(calc)

---

first i get this error : 

---

Error in library(functional) : there is no package called ‘functional’

---

I installed the package , but still gives me the same error , so after reading a lot of discussion about path and that R doesn't know where functional is , i did 
.libPath() and i copied the package functional in all the directories that i've seen .
ok now it tells me this:
so i copied rmr2 too like i did with functionnal , but nothing happend , there is the full error : 

---

Loading objects:
  dataPath
  header
  ints
Warning: namespace ‘rmr2’ is not available and has been replaced
by .GlobalEnv when processing object ‘ints’
  query
  .Random.seed
  set
  small.ints
  useMapreduce
Loading objects:
  backend.parameters
  combine
  combine.file
  combine.line
  debug
  default.input.format
Warning: namespace ‘rmr2’ is not available and has been replaced
by .GlobalEnv when processing object ‘default.input.format’
  default.output.format
  in.folder
  in.memory.combine
  input.format
  libs
  map
  map.file
  map.line
  out.folder
  output.format
  pkg.opts
  postamble
  preamble
  profile.nodes
  reduce
  reduce.file
  reduce.line
  rmr.global.env
  rmr.local.env
  save.env
  tempfile
  vectorized.reduce
  verbose
  work.dir
Loading required package: methods
Loading required package: rmr2
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Warning in FUN(X[[i]], ...) : can't load rmr2
Loading required package: rJava
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rJava’
Warning in FUN(X[[i]], ...) : can't load rJava
Loading required package: rhdfs
Warning in library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘rhdfs’
Warning in FUN(X[[i]], ...) : can't load rhdfs
Loading objects:
  backend.parameters
  combine
  combine.file
  combine.line
  debug
  default.input.format
Warning: namespace ‘rmr2’ is not available and has been replaced
by .GlobalEnv when processing object ‘default.input.format’
  default.output.format
  in.folder
  in.memory.combine
  input.format
  libs
  map
  map.file
  map.line
  out.folder
  output.format
  pkg.opts
  postamble
  preamble
  profile.nodes
  reduce
  reduce.file
  reduce.line
  rmr.global.env
  rmr.local.env
  save.env
  tempfile
  vectorized.reduce
  verbose
  work.dir
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
No traceback available 
Error during wrapup: 
Execution halted

---

Any help is appreciated , thank you .

**Comment by viveknk** [comment]
How was this issue solved? What was the mistake/correction?
