### ISSUE TITLE
Job hangs after 100% Map and 100% Reduce

### ISSUE THREAD

**Issue by guptam** [RevolutionAnalytics/rmr2#62]
Hi,

I am facing a issue while performing random forest regression using rmr2.  Below are the details:

This is my mapper, which partitions the dataset for each User coming 
in the first column of dataset

userPartitionMapper <- function(k,v) { keyval(v[1], v) }

This is my reducer that for each user (around 200), create a RF model for 
to predict user's rating based on movies attributes (Plot keywords, Genres, 
Actor, Country, language etc.) - total 15,040 attributes

RandomForestGenerator <- function(k,v) 
{
    rf <- randomForest(formula=UserRatingScaled~.-UserID-MovieID,
                        data=v,
                        ntree=10)
    keyval(k, list(forest=rf))
}

Issue what I am facing is, that after running this Hadoop Streaming Job, it get's completed till Map=100%, Reduce=100%. And then it STOPS. No error, no warning, no status. I tried looking at the Jobtracker and TaskTracker logs. But couldn't figure out anything.

This is random in nature, and sometime even my RStudio crashes and restart.

Total dataset size is pretty small ~ 800 MB, and I am running this is on 7 node Hadoop cluster  (1 namenode+Jobtracker, and 6 datanodes + Tasktrackers).

I am still debugging this, but opening this issue, just in case people have experienced this before. Any pointers will be highly appreciated.

BTW - RHadoop Rocks...!!!

Thanks,
Manish

**Comment by akshatsehgal01** [comment]
how did you fix it?
